// Stripe Payment Links — LIVE MODE (produção)
// Gerados via scripts/stripe-bootstrap.js com sk_live_ key
const STRIPE_LINKS = {
  'receitas-low-carb':     'https://buy.stripe.com/7sY00jeibeBjfCLeG35sA00',
  'planilhas-treino':      'https://buy.stripe.com/eVqaEXca3ctb4Y77dB5sA01',
  'receitas-indigenas':    'https://buy.stripe.com/bJe14nfmf64Nair8hF5sA02',
  'templates-notion':      'https://buy.stripe.com/4gM7sL5LF1OxgGP0Pd5sA03',
  'ebooks-autoajuda':      'https://buy.stripe.com/14AdR9b5Z8cV8ajbtR5sA04',
  'planilhas-financeiras': 'https://buy.stripe.com/28E8wPeibbp7duD0Pd5sA05',
  'kit-completo':          'https://buy.stripe.com/00w8wPca3eBj9en0Pd5sA06',
  'life-os':               'https://buy.stripe.com/cNidR98XRbp7eyH0Pd5sA07',
}
const STRIPE = (slug) => STRIPE_LINKS[slug]

// Stripe Price IDs — necessários pra criar Checkout Sessions dinâmicas (com order bump)
// Match: gerados via scripts/stripe-bootstrap.js (LIVE mode)
export const STRIPE_PRICES = {
  'receitas-low-carb':     'price_1TRNu0Fl5Mui7NRgQHCV7etc',
  'planilhas-treino':      'price_1TRNu2Fl5Mui7NRg10yWSTRj',
  'receitas-indigenas':    'price_1TRNu3Fl5Mui7NRg6w5SFF3r',
  'templates-notion':      'price_1TRNu5Fl5Mui7NRgC43w62O2',
  'ebooks-autoajuda':      'price_1TRNu6Fl5Mui7NRgKgCaTdPj',
  'planilhas-financeiras': 'price_1TRNu8Fl5Mui7NRga8KDW8m5',
  'kit-completo':          'price_1TRNu9Fl5Mui7NRgXu4aRPLN',
  'life-os':               'price_1TRNuBFl5Mui7NRgrz7Z9pNy',
}

export const PRODUCTS = {
  'receitas-low-carb': {
    slug: 'receitas-low-carb',
    emoji: '🥗',
    image: '/assets/products/receitas-low-carb.png',
    // Vídeo do "Tudo que você vai receber" (scroll dentro do app/PDF). Auto-play, loop, sem som.
    // Quando estiver null, mostra a imagem (image) como fallback automático.
    // Pra ativar: suba o MP4 em public/assets/products/ e troque null por '/assets/products/seu-arquivo.mp4'
    // Recomendado: MP4 H.264, vertical 9:16 ou 4:5, 8-15s, < 5MB, sem áudio.
    whatYouGetVideo: '/assets/low-carb-preview.mp4',
    whatYouGetPoster: '/assets/products/receitas-low-carb.png',
    transformImage: '/assets/products/low-carb-antes-depois.png',
    appTour: [
      { icon: '🍳', title: 'Receitas', desc: '30 receitas filtráveis por refeição, tempo, busca. Modal com macros + ingredientes + preparo.' },
      { icon: '📅', title: 'Planejador', desc: 'Grid 7 dias × 4 refeições. Toque, escolhe receita, semana montada em 2 minutos.' },
      { icon: '🛒', title: 'Lista de Compras', desc: 'Auto-gerada do planejamento. Agrupada por seção do mercado. WhatsApp num toque.' },
      { icon: '📊', title: 'Nutrição', desc: '40 alimentos low carb com macros. Filtra os de baixíssimo carb (<5g).' },
      { icon: '📚', title: 'Guia', desc: 'Protocolo, alimentos SIM/NÃO, sintomas, FAQ com 10 perguntas.' },
    ],
    title: 'O app low carb que finalmente vai te fazer emagrecer',
    subtitle: '30 receitas + planejador semanal + lista de compras automática + tabela nutricional + guia completo. Tudo num sistema funcional, no seu celular.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('receitas-low-carb'),
    color: 'from-green-600 to-emerald-500',
    badge: 'MAIS VENDIDO',
    category: 'alimentacao',
    // 4 pilares — sistema/app, não ebook
    benefits: [
      { icon: '📱', title: 'Sistema, não PDF', desc: 'Funciona no celular, tablet, computador. Online ou offline. Não precisa baixar nada.' },
      { icon: '🗓️', title: 'Planejador semanal', desc: 'Monta sua semana com 1 toque. Café, almoço, lanche, jantar — pronto pra seguir.' },
      { icon: '🛒', title: 'Lista de compras automática', desc: 'Escolheu suas receitas? Sua lista do mercado já tá pronta — agrupada por seção.' },
      { icon: '📊', title: 'Tabela nutricional + guia', desc: 'Saiba o que comer, quanto, e por quê. 40 alimentos analisados + guia completo low carb.' },
    ],
    // Mantém pain points pra seção dedicada (mulher 28-50, frustrada com dietas)
    painPoints: [
      'Você já começou a dieta segunda e desistiu na quarta — de novo?',
      'Olha pro espelho e não reconhece mais o seu corpo?',
      'Cansada de comer "frango com batata doce" todo santo dia?',
      'Não tem 2 horas livres pra ficar na cozinha — a vida é corrida?',
      'A balança trava e ninguém te explica o porquê?',
    ],
    whatYouGet: [
      { item: '30 receitas low carb com macros calculados (café, almoço, jantar, lanche)', value: 'R$47' },
      { item: 'Planejador semanal interativo — monte sua semana com 1 toque', value: 'R$39' },
      { item: 'Lista de compras automática — agrupada por seção do mercado', value: 'R$29' },
      { item: 'Tabela nutricional de 40 alimentos low carb (carbs, proteína, gordura, fibra)', value: 'R$25' },
      { item: 'Guia completo low carb — protocolo, alimentos SIM/NÃO, FAQ', value: 'R$25' },
      { item: 'Acesso pelo celular, tablet ou pc — funciona offline', value: 'R$19' },
      { item: 'BÔNUS: Compartilhar lista de compras direto no WhatsApp', value: 'R$10' },
    ],
    testimonials: [
      { name: 'Ana Paula, 38', city: 'São Paulo, SP', text: 'Perdi 8kg em 2 meses sem passar fome. Voltei a usar as roupas que tava guardando há 4 anos. Minha autoestima voltou.', stars: 5, avatar: '👩' },
      { name: 'Mariana, 42', city: 'Belo Horizonte, MG', text: 'Eu odiava cozinhar. Achava que comida saudável era cara e sem gosto. Esse guia mudou tudo — meu marido e meus filhos comem junto comigo.', stars: 5, avatar: '👩‍🦰' },
      { name: 'Carla, 31', city: 'Curitiba, PR', text: 'Em 3 semanas perdi 4kg e a barriga sumiu. O melhor: não senti fome NENHUMA VEZ. Recomendei pra todas as amigas do trabalho.', stars: 5, avatar: '👩‍🦱' },
    ],
    faq: [
      { q: 'É um ebook ou um app?', a: 'É um app — um sistema funcional que abre no navegador do celular, tablet ou pc. Não é um PDF estático. Você navega entre receitas, monta seu planejamento da semana, gera sua lista de compras automaticamente, consulta a tabela nutricional. Tudo sincronizado e editável.' },
      { q: 'Preciso baixar algum aplicativo na loja?', a: 'Não precisa. Funciona direto no navegador. Mas se quiser, dá pra "instalar" o atalho na tela inicial do celular pra abrir igual app.' },
      { q: 'Funciona offline?', a: 'Sim. Depois que você abrir uma vez com internet, o sistema fica salvo no seu celular e funciona offline.' },
      { q: 'Preciso saber cozinhar?', a: 'Não. As 30 receitas têm passo-a-passo simples e levam no máximo 30 minutos. Pensadas pra quem nunca pegou numa panela.' },
      { q: 'Vou passar fome?', a: 'Não. Low carb feito direito reduz a fome porque proteína e gordura boa saciam por horas. As receitas têm macros calculados pra você comer até ficar satisfeita.' },
      { q: 'Os ingredientes são caros?', a: 'Tudo no mercado da esquina. A lista de compras automática otimiza pra você gastar menos do que gastava antes.' },
      { q: 'Como recebo o acesso?', a: 'Imediato. Após o pagamento, link no email em até 2 minutos. Acesso vitalício, sem mensalidade.' },
      { q: 'Funciona pra diabéticos ou hipertensos?', a: 'Low carb é frequentemente recomendado pra controle glicêmico e pressão. Mas sempre consulte seu médico antes de mudar a alimentação.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. Manda um email e devolvemos 100% do valor, sem pergunta.' },
    ],
    relatedSlugs: ['receitas-indigenas', 'planilhas-financeiras', 'ebooks-autoajuda'],
  },

  'planilhas-treino': {
    slug: 'planilhas-treino',
    emoji: '💪',
    image: '/assets/products/planilhas-treino.png',
    transformImage: null,
    whatYouGetVideo: null,
    whatYouGetPoster: '/assets/products/planilhas-treino.png',
    title: 'O sistema de treino que substitui seu personal — sem precisar pagar R$300/mês',
    subtitle: '12 semanas de treino periodizado + tracker de evolução + vídeos de execução. Academia ou casa, iniciante ou avançado.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('planilhas-treino'),
    color: 'from-orange-600 to-amber-500',
    badge: 'MAIS COMPLETO',
    category: 'treinos',
    benefits: [
      { icon: '📅', title: 'Periodização inteligente', desc: '12 semanas progressivas — seu corpo nunca se acostuma, sempre evolui' },
      { icon: '🏠', title: 'Casa OU academia', desc: 'Duas versões completas — você treina onde quiser, sem desculpa' },
      { icon: '📹', title: 'Vídeos de execução', desc: 'Cada exercício tem QR pra vídeo — você vê exatamente como fazer' },
      { icon: '📊', title: 'Tracker de evolução', desc: 'Anota cargas, séries e medidas — vê preto-no-branco que tá evoluindo' },
    ],
    painPoints: [
      'Chega na academia e fica olhando os outros sem saber o que fazer?',
      'Treina há 6 meses e o espelho continua igual?',
      'Personal cobra R$200-300/mês e você não pode bancar?',
      'Quer treinar em casa mas não tem ideia de como montar uma sequência?',
      'Já tentou app de treino genérico e abandonou em 2 semanas?',
    ],
    whatYouGet: [
      { item: '12 semanas de treino periodizado (iniciante → intermediário → avançado)', value: 'R$49' },
      { item: 'Versão academia COMPLETA — todos os equipamentos padrão', value: 'R$29' },
      { item: 'Versão casa COMPLETA — só com peso do corpo (calistenia)', value: 'R$29' },
      { item: 'Vídeos de execução de TODOS os exercícios (acesso por QR Code)', value: 'R$39' },
      { item: 'Tracker editável de cargas, séries e medidas semanais', value: 'R$19' },
      { item: 'Guia de nutrição pré e pós-treino (o que comer e quando)', value: 'R$19' },
      { item: 'BÔNUS: Tabela de substituição de exercícios (não tem barra? troca por X)', value: 'R$15' },
    ],
    testimonials: [
      { name: 'Ricardo, 34', city: 'Rio de Janeiro, RJ', text: 'Em 3 meses usando a planilha ganhei 4kg de massa magra e perdi 2cm de cintura. Meu personal cobrava R$280/mês — economizei mais de R$800.', stars: 5, avatar: '👨' },
      { name: 'Fernanda, 29', city: 'Porto Alegre, RS', text: 'Mãe de 2, sem tempo de academia. A versão casa salvou minha vida. Treino enquanto as crianças dormem. Em 4 meses voltei pra mesma calça que usava antes da gravidez.', stars: 5, avatar: '👩' },
      { name: 'Bruno, 41', city: 'Brasília, DF', text: 'Sempre treinei errado, sem progressão. Em 8 semanas seguindo o programa, supino subiu de 60kg pra 85kg. Funciona porque é estruturado.', stars: 5, avatar: '👨‍🦱' },
    ],
    faq: [
      { q: 'É um app ou um PDF?', a: 'É um sistema interativo no navegador (celular, tablet, pc). Você vê o treino do dia, marca o que fez, anota cargas, vê seus gráficos de evolução. Não é PDF estático.' },
      { q: 'Funciona pra iniciante absoluto?', a: 'Sim. As semanas 1-4 são feitas pra quem nunca pegou peso. Aprendizado de movimento + adaptação. Depois o programa progride sozinho.' },
      { q: 'Em quanto tempo vejo resultado?', a: 'Força e disposição em 2-3 semanas. Mudança visual em 6-8 semanas (com alimentação alinhada). Hipertrofia consistente em 12 semanas.' },
      { q: 'Preciso de equipamento em casa?', a: 'Não. A versão casa é 100% calistenia (peso do corpo). Toalha + cadeira + chão = tudo que precisa.' },
      { q: 'Sou mulher, vai me deixar musculosa demais?', a: 'Não. Mulher tem ~10x menos testosterona que homem — fisiologicamente impossível ficar "musculosa" sem suplementação extrema. Você vai ficar tonificada e forte.' },
      { q: 'Como recebo o acesso?', a: 'Imediato. Após o pagamento, link no email em até 2 minutos. Acesso vitalício, sem mensalidade.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. Manda email e devolvemos 100%, sem pergunta nenhuma.' },
    ],
    relatedSlugs: ['receitas-low-carb', 'ebooks-autoajuda', 'planilhas-financeiras'],
  },

  'receitas-indigenas': {
    slug: 'receitas-indigenas',
    emoji: '🌿',
    image: '/assets/products/receitas-indigenas.png',
    transformImage: null,
    whatYouGetVideo: null,
    whatYouGetPoster: '/assets/products/receitas-indigenas.png',
    title: 'A culinária ancestral que cura — 60+ receitas indígenas que sua avó conhecia',
    subtitle: 'Comida nutritiva, simples e cheia de história. Reconecte com sabores brasileiros autênticos — sem glúten, sem industrializado, com ingredientes que a terra dá.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('receitas-indigenas'),
    color: 'from-amber-600 to-orange-500',
    badge: 'EXCLUSIVO',
    category: 'indigenas',
    benefits: [
      { icon: '🌱', title: 'Ingredientes que a terra dá', desc: 'Mandioca, milho, peixe, frutas nativas — tudo natural, nada industrializado' },
      { icon: '⚕️', title: 'Sabedoria medicinal', desc: 'Cada receita tem nota dos benefícios — anti-inflamatório, digestivo, energético' },
      { icon: '🌾', title: 'Sem glúten naturalmente', desc: '90% das receitas já são naturalmente sem glúten — sabor sem complicação' },
      { icon: '👨‍👩‍👧', title: 'Família inteira come', desc: 'Receitas com versão pra crianças marcadas — todos comem junto' },
    ],
    painPoints: [
      'Cansada de comer sempre as mesmas 5 receitas todo mês?',
      'Sente que comida industrializada tá fazendo mal pra você e sua família?',
      'Quer alimentação mais natural mas não sabe por onde começar?',
      'Tem intolerância ao glúten e cansou de receita "free-from" que não tem sabor?',
      'Quer reconectar com sabores brasileiros autênticos — não com tendência gringa de TikTok?',
    ],
    whatYouGet: [
      { item: '60+ receitas ancestrais ilustradas (origem, história, modo de preparo)', value: 'R$39' },
      { item: 'Guia de ingredientes nativos — onde achar fora da Amazônia', value: 'R$19' },
      { item: 'Notas medicinais de cada ingrediente (uso indígena tradicional)', value: 'R$25' },
      { item: 'Versão vegana e sem glúten de cada receita marcada', value: 'R$19' },
      { item: 'Dicionário de plantas medicinais brasileiras (40 plantas)', value: 'R$15' },
      { item: 'Receitas pra crianças — marcadas com selo "família"', value: 'R$15' },
      { item: 'BÔNUS: 10 receitas de bebidas ancestrais (chás, sucos, fermentados)', value: 'R$15' },
    ],
    testimonials: [
      { name: 'Juliana, 47', city: 'Manaus, AM', text: 'Redescobri sabores da casa da minha avó indígena que eu tinha esquecido. Minha mãe ligou chorando quando provou o tucupi. Conexão de verdade.', stars: 5, avatar: '👩‍🦳' },
      { name: 'Tatiane, 35', city: 'Florianópolis, SC', text: 'Filho com intolerância ao glúten. As receitas são naturalmente sem glúten — primeira vez que ele come com a família sem precisar de prato separado.', stars: 5, avatar: '👩' },
      { name: 'Marcos, 52', city: 'Belém, PA', text: 'Comida indígena de verdade, não a versão de chef caro. Ingredientes simples do mercado, sabor que não tem em restaurante nenhum.', stars: 5, avatar: '👨‍🦲' },
    ],
    faq: [
      { q: 'É um app ou ebook?', a: 'É um app no navegador. Você navega entre as 60 receitas, filtra por origem (Amazônia, Cerrado, Atlântica), busca por ingrediente ou benefício medicinal.' },
      { q: 'Os ingredientes são caros ou difíceis de achar?', a: 'A maioria você acha em mercado normal: mandioca, milho, peixe, frutas. Pra ingredientes mais regionais (tucupi, jambu) indicamos substitutos e onde comprar online.' },
      { q: 'É muito complicado de fazer?', a: 'Não. A culinária indígena é simples por natureza — poucos ingredientes, fogo, tempo. Não tem técnica francesa nem ferramenta cara.' },
      { q: 'Funciona pra família com crianças?', a: 'Sim. Marcamos as receitas "pra família" — sabores suaves, sem pimenta, fáceis de mastigar. Ótima introdução pra crianças aceitarem comida de verdade.' },
      { q: 'Tem receita pra quem é vegano?', a: 'Sim. 25 das 60 receitas são naturalmente veganas (mandioca, milho, frutas, plantas). Outras têm versão vegana adaptada.' },
      { q: 'Como recebo o acesso?', a: 'Imediato. Após o pagamento, link no email em 2 minutos. Acesso vitalício.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. 100% do valor devolvido.' },
    ],
    relatedSlugs: ['receitas-low-carb', 'ebooks-autoajuda', 'templates-notion'],
  },

  'templates-notion': {
    slug: 'templates-notion',
    emoji: '🛠️',
    image: '/assets/products/templates-notion.png',
    transformImage: null,
    whatYouGetVideo: null,
    whatYouGetPoster: '/assets/products/templates-notion.png',
    title: '7 ferramentas interativas que substituem 10 apps que você paga',
    subtitle: 'Wheel of Life · Planejador 90 dias · GTD · CRM Pessoal · Tracker de Leituras · Calculadora FIRE · Diário de Hábitos. Tudo no nosso app, sem Notion, sem mensalidade.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('templates-notion'),
    color: 'from-pink-600 to-rose-500',
    badge: 'PRODUTIVIDADE',
    category: 'notion',
    benefits: [
      { icon: '⚡', title: 'Acesso instantâneo', desc: 'Abre, usa, salva. Sem precisar configurar Notion, criar conta, fazer template.' },
      { icon: '🛠️', title: '7 ferramentas reais', desc: 'Cada uma com cálculos automáticos, persistência local e copia-e-cola integrado.' },
      { icon: '💸', title: 'Pagamento único', desc: 'Sem mensalidade. Sem plano. Acesso vitalício. Sem cobrança recorrente.' },
      { icon: '📱', title: 'Funciona offline', desc: 'Celular, tablet, pc. Salva tudo no seu dispositivo — sem depender de cloud externo.' },
    ],
    painPoints: [
      'Já tentou montar template no Notion e desistiu no meio do caminho?',
      'Paga mensalidade de 3 apps de produtividade que mal usa?',
      'Tem ideias na cabeça mas perde porque não tem onde anotar rápido?',
      'Quer organizar metas e hábitos mas não sabe por onde começar?',
      'Cansa de ferramenta complicada que toma mais tempo do que economiza?',
    ],
    whatYouGet: [
      { item: 'Wheel of Life — avalie 10 áreas da sua vida com gráfico visual', value: 'R$25' },
      { item: 'Planejador 90 Dias — quebre meta grande em 12 sprints semanais', value: 'R$29' },
      { item: 'Caixa de Entrada GTD — capture, processe, execute (método validado)', value: 'R$25' },
      { item: 'CRM Pessoal — gerencie clientes, follow-ups e propostas (pra freelancer)', value: 'R$35' },
      { item: 'Tracker de Leituras — livros, progresso, notas, rating', value: 'R$15' },
      { item: 'Calculadora FIRE — descubra quando você atinge independência financeira', value: 'R$25' },
      { item: 'Diário de Hábitos — calendário visual de 30 dias com check', value: 'R$19' },
    ],
    testimonials: [
      { name: 'Letícia, 28', city: 'São Paulo, SP', text: 'Tentei Notion 3 vezes. Sempre desistia no setup. Aqui é abrir e usar — em 5 minutos tava planejando os próximos 90 dias. Salvou minha sanidade.', stars: 5, avatar: '👩‍💻' },
      { name: 'Pedro, 33', city: 'Recife, PE', text: 'Freelancer de design. Usava Trello + planilha + caderno pra controlar clientes. Agora tudo no CRM Pessoal — esqueci de cobrar 0 vezes em 2 meses.', stars: 5, avatar: '👨‍💼' },
      { name: 'Roberta, 36', city: 'Goiânia, GO', text: 'Wheel of Life me fez ver que carreira tava em 9 mas saúde em 3. Mudei minhas prioridades em uma tarde. Ferramenta simples, impacto grande.', stars: 5, avatar: '👩‍🎨' },
    ],
    faq: [
      { q: 'Preciso ter conta no Notion?', a: 'Não. Esse produto é independente do Notion. As ferramentas são nossas, rodam direto no nosso app — sem precisar de Notion, Trello, ou outro app externo.' },
      { q: 'Como acesso?', a: 'Compra → email → link → abre no celular ou pc. Em 30 segundos você tá usando a primeira ferramenta. Acesso vitalício.' },
      { q: 'Funciona offline?', a: 'Sim. Depois de abrir uma vez com internet, fica salvo no seu dispositivo. Você pode usar até no avião.' },
      { q: 'Os dados ficam onde?', a: 'No seu dispositivo (localStorage do navegador). Privacidade total — nada vai pra nossa nuvem.' },
      { q: 'É similar ao Notion?', a: 'É mais focado. Notion é genérico — você precisa criar tudo. Aqui são 7 ferramentas prontas, cada uma resolvendo um problema específico.' },
      { q: 'Atualiza com novidades?', a: 'Sim. Quando lançamos novas ferramentas ou melhorias, você recebe automaticamente — sem custo extra.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. Manda email e devolvemos 100%, sem pergunta.' },
    ],
    relatedSlugs: ['ebooks-autoajuda', 'planilhas-financeiras', 'planilhas-treino'],
  },

  'ebooks-autoajuda': {
    slug: 'ebooks-autoajuda',
    emoji: '🧠',
    image: '/assets/products/ebooks-autoajuda.png',
    transformImage: null,
    whatYouGetVideo: null,
    whatYouGetPoster: '/assets/products/ebooks-autoajuda.png',
    title: 'Os 5 livros que faltavam pra você sair da estagnação',
    subtitle: 'Disciplina, mentalidade, foco, limites e realização. 5 ebooks brasileiros, diretos, sem coach gringo. Para quem quer agir, não só ler.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('ebooks-autoajuda'),
    color: 'from-violet-600 to-purple-500',
    badge: 'TRANSFORMADOR',
    category: 'autoajuda',
    benefits: [
      { icon: '🎯', title: 'Direto ao ponto', desc: 'Cada livro 60-80 páginas. Zero enrolação. Você lê em 2-3h e aplica.' },
      { icon: '🇧🇷', title: 'Realidade brasileira', desc: 'Não é tradução de gringo. Foi escrito pensando na vida do brasileiro' },
      { icon: '⚡', title: 'Acionável de imediato', desc: 'Cada capítulo termina com exercício prático — você aplica, não só lê' },
      { icon: '📚', title: '5 temas que se conectam', desc: 'Disciplina + mentalidade + foco + limites + metas — sistema completo' },
    ],
    painPoints: [
      'Sabe o que precisa fazer mas trava na hora de começar?',
      'Procrastina manhã inteira e à noite sente que perdeu o dia?',
      'Já leu 50 livros de autoajuda e nada mudou de verdade?',
      'Começa projetos com toda força e abandona em 2 semanas?',
      'Sente que tá vivendo no piloto automático e o tempo tá passando?',
    ],
    whatYouGet: [
      { item: '"A Arte da Disciplina" — como criar hábitos que duram (60 páginas + 12 exercícios)', value: 'R$25' },
      { item: '"Mentalidade de Crescimento" — desbloqueie o potencial (70 páginas)', value: 'R$25' },
      { item: '"Foco Total" — método de eliminação de distração (65 páginas)', value: 'R$25' },
      { item: '"O Poder do Não" — limites que liberam tempo e energia (55 páginas)', value: 'R$19' },
      { item: '"Realização em 90 dias" — método prático de metas trimestrais (75 páginas)', value: 'R$29' },
      { item: 'Worksheet integrada dos 5 livros (PDF editável)', value: 'R$15' },
      { item: 'BÔNUS: Áudio-versão de cada ebook (formato podcast pra ouvir no carro/academia)', value: 'R$25' },
    ],
    testimonials: [
      { name: 'Carolina, 32', city: 'Campinas, SP', text: 'Li os 5 em 6 semanas, fazendo os exercícios. Mudou minha relação com trabalho e com prazos pessoais. Não é mais um livro genérico — tem método.', stars: 5, avatar: '👩‍🎓' },
      { name: 'Thiago, 39', city: 'Salvador, BA', text: 'Sempre fui aquele que comprava livro e nunca terminava. Esses são curtos e diretos. "A Arte da Disciplina" me fez sair de 2h/dia de procrastinação pra 30 minutos.', stars: 5, avatar: '👨' },
      { name: 'Aline, 27', city: 'Fortaleza, CE', text: 'Trabalho remoto, sem chefe pra cobrar. Aplicando o método de 90 dias em 2 trimestres dobrei minha renda como designer. Não é hype — funciona.', stars: 5, avatar: '👩‍🦱' },
    ],
    faq: [
      { q: 'É um app ou PDF?', a: 'Os ebooks são PDFs otimizados pra celular + áudio (mp3). Você baixa e lê/ouve onde quiser, sempre.' },
      { q: 'São tradução ou original?', a: '100% original. Escritos em português brasileiro pensando na nossa realidade — chefe brasileiro, família brasileira, problemas brasileiros.' },
      { q: 'Quanto tempo pra ler tudo?', a: 'Cada ebook leva 2-3 horas. Lendo 1 por semana = 5 semanas. Mas o impacto vem quando você FAZ os exercícios — aí é 1 trimestre de aplicação.' },
      { q: 'Tem áudio mesmo?', a: 'Sim. Cada ebook tem versão em áudio (formato podcast) pra ouvir dirigindo, na academia ou caminhando. Vale como bônus.' },
      { q: 'Funciona pra quem nunca leu autoajuda?', a: 'Especialmente pra quem nunca leu. Linguagem direta, sem jargão coach, sem "abundância energética". Tudo prático.' },
      { q: 'Como recebo?', a: 'Imediato. Após o pagamento, link no email em 2 minutos. Acesso vitalício aos PDFs e áudios.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. Devolvemos 100% sem pergunta nenhuma.' },
    ],
    relatedSlugs: ['templates-notion', 'planilhas-financeiras', 'receitas-low-carb'],
  },

  'planilhas-financeiras': {
    slug: 'planilhas-financeiras',
    emoji: '💰',
    image: '/assets/products/planilhas-financeiras.png',
    transformImage: null,
    whatYouGetVideo: null,
    whatYouGetPoster: '/assets/products/planilhas-financeiras.png',
    title: 'O sistema que vai te tirar do vermelho — e fazer seu dinheiro sobrar',
    subtitle: '8 planilhas com cálculos automáticos: gastos + dívidas + reserva + metas + investimentos. Você abre, digita os números, e o sistema mostra exatamente o que fazer.',
    price: 27.90,
    installment: { times: 3, value: 9.30 },
    originalPrice: 97.00,
    checkoutUrl: STRIPE('planilhas-financeiras'),
    color: 'from-indigo-600 to-blue-500',
    badge: 'ESSENCIAL',
    category: 'financas',
    benefits: [
      { icon: '🧮', title: 'Cálculo automático', desc: 'Você digita seus gastos, a planilha faz a conta. Vê preto-no-branco pra onde vai o dinheiro.' },
      { icon: '🎯', title: 'Método bola-de-neve', desc: 'Pra sair de dívida na ordem certa — método validado que economiza meses de juros' },
      { icon: '📊', title: 'Dashboard visual', desc: 'Gráficos automáticos do ano. Você vê padrão de gasto e ajusta na hora' },
      { icon: '💵', title: 'Funciona pra MEI também', desc: 'Planilha específica pra autônomo/MEI controlar receita variável + impostos' },
    ],
    painPoints: [
      'Salário cai dia 5, no dia 20 você não sabe onde gastou?',
      'Tenta poupar R$100/mês e nunca consegue?',
      'Tem 3 dívidas (cartão, cheque especial, parcelamento) e não sabe qual pagar primeiro?',
      'Quer investir mas tá vivendo no rotativo do cartão?',
      'É autônomo/MEI e mistura dinheiro pessoal com da empresa?',
    ],
    whatYouGet: [
      { item: 'Planilha de controle mensal de gastos com 18 categorias', value: 'R$25' },
      { item: 'Planejador anti-dívida com método bola-de-neve (cálculo automático)', value: 'R$29' },
      { item: 'Calculadora de reserva de emergência personalizada', value: 'R$15' },
      { item: 'Planilha de metas financeiras anuais com checkpoint trimestral', value: 'R$19' },
      { item: 'Dashboard financeiro anual com gráficos (renda, gasto, sobra, evolução)', value: 'R$35' },
      { item: 'Planilha pra MEI/autônomo (receita variável + impostos + pró-labore)', value: 'R$25' },
      { item: 'BÔNUS: Calculadora de juros compostos pra investimentos', value: 'R$15' },
    ],
    testimonials: [
      { name: 'Sandra, 41', city: 'São Paulo, SP', text: 'Tava em R$3.200 de dívida no rotativo. Em 4 meses seguindo o método bola-de-neve quitei tudo. Hoje tenho R$1.800 de reserva. Nunca achei que conseguiria.', stars: 5, avatar: '👩' },
      { name: 'Eduardo, 35', city: 'Curitiba, PR', text: 'Sempre achei que ganhava pouco. Quando vi o dashboard, descobri que gastava R$680/mês em delivery. Cortei pra R$200 e em 3 meses comecei a investir.', stars: 5, avatar: '👨‍💼' },
      { name: 'Priscila, 29', city: 'Porto Alegre, RS', text: 'Trabalho como freela, renda super variável. A planilha pra MEI me salvou — sei exatamente quanto guardar pra impostos, quanto é meu pra gastar. Dormi melhor desde então.', stars: 5, avatar: '👩‍🦰' },
    ],
    faq: [
      { q: 'É um app ou planilha?', a: 'É um sistema com 8 planilhas interconectadas que funcionam no Google Sheets (grátis) ou Excel. Tem cálculos automáticos, gráficos, alertas. Mais robusto que app de finanças básico.' },
      { q: 'Funciona no celular?', a: 'Sim. Google Sheets tem app gratuito pra Android/iOS. Você abre, digita gastos, a planilha calcula tudo.' },
      { q: 'Precisa saber Excel?', a: 'Não. Tudo é digitar valor em célula amarela. As fórmulas estão prontas, escondidas. Só você usa.' },
      { q: 'Sirvo se for MEI?', a: 'Especialmente. Tem uma planilha exclusiva pra MEI/autônomo separar receita pessoal × empresa, calcular impostos e pró-labore.' },
      { q: 'Quanto tempo pra ver resultado?', a: 'Visual: imediato (você vê pra onde vai o dinheiro no 1º mês). Concreto: pessoas saem de dívida em 3-6 meses, formam reserva em 6-12 meses.' },
      { q: 'Tem suporte se eu travar?', a: 'Cada planilha tem aba "Como usar" com vídeo. Email de dúvida tem resposta em 24h.' },
      { q: 'E se eu não gostar?', a: 'Garantia incondicional de 7 dias. 100% do valor de volta, sem pergunta.' },
    ],
    relatedSlugs: ['templates-notion', 'ebooks-autoajuda', 'planilhas-treino'],
  },
}

export const ALL_PRODUCT_SLUGS = Object.keys(PRODUCTS)

export const getProduct = (slug) => PRODUCTS[slug] || null

export const getRelatedProducts = (slug) => {
  const product = PRODUCTS[slug]
  if (!product) return []
  return product.relatedSlugs.map(s => PRODUCTS[s]).filter(Boolean)
}

export const KIT_COMPLETO = {
  title: 'Kit Completo — Todos os 6 Produtos',
  description: 'Leve todos os produtos por um preço especial e transforme todas as áreas da sua vida',
  bumpPrice: 47.00,
  bumpInstallment: { times: 3, value: 15.67 },
  totalValue: 167.40,
  checkoutUrl: STRIPE('kit-completo'),
  items: ALL_PRODUCT_SLUGS.map(s => PRODUCTS[s].title),
}

export const LIFE_OS = {
  slug: 'life-os',
  emoji: '⚡',
  title: 'Life OS — Sistema Completo + Biblioteca dos 6 Produtos',
  subtitle: 'O único plano que entrega: app gamificado, biblioteca completa e novos materiais todo mês',
  price: 59.90,
  installment: { times: 3, value: 19.97 },
  monthlyAfter: 79.90,
  originalPrice: 127.00,
  description: 'Tudo em um só lugar: o sistema para executar (hábitos, treinos, journal, finanças) + a biblioteca completa com os 6 produtos + materiais novos todo mês. Cancele quando quiser.',
  checkoutUrl: STRIPE('life-os'),
  features: [
    'Acesso completo à biblioteca dos 6 produtos (Receitas Low Carb, Treinos, Indígenas, Templates, Ebooks, Financeiras)',
    'Novos materiais adicionados todo mês — sempre evoluindo',
    'App gamificado: tracker de hábitos com streak e XP',
    'Diário de treinos com histórico completo',
    'Controle financeiro integrado',
    'Sistema de metas com barra de progresso',
    'Journal diário com mood tracker',
    'Timer Pomodoro focado',
    'Sistema de gamificação com 10 níveis',
    'Dashboard de estatísticas em tempo real',
  ],
}
